apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: consul
spec:
  releaseName: consul
  chart:
    spec:
      chart: consul
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      version: "0.18.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
