apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
  - ../../base/vault
configMapGenerator:
  - name: vault-values
    files:
      - values.yaml=override-values.yaml
configurations:
  - kustomizeconfig.yaml
patchesStrategicMerge:
  - values.yaml