apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
spec:
  releaseName: vault
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      version: "0.18.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
  - kind: ConfigMap
   # Generate config map in Kustomization.yaml which is created from values.yaml
    name: vault-values